from article import articles


PERSONA_NEW_ARTICLES = [
    articles.DO_RESEARCH_FIRST,
    articles.KNOW_YOUR_CUSTOMER,
    articles.MEET_YOUR_CUSTOMER,
    articles.MANAGE_LANGUAGE_DIFFERENCES,
    articles.GET_MONEY_TO_EXPORT,
    articles.MAKE_EXPORTING_PLAN,
    articles.FIND_A_ROUTE_TO_MARKET,
    articles.USE_OVERSEAS_AGENT,
    articles.USE_DISTRIBUTOR,
    articles.CONSIDER_HOW_PAID,
    articles.PLAN_THE_LOGISTICS,
    articles.INTERNATIONALISE_WESBITE,
    articles.WHAT_INTERLECTUAL_PROPERTY_IS,
    articles.TYPES_OF_INTERLECTUAL_PROPERTY,
]

PERSONA_OCCASIONAL_ARTICLES = [
    articles.DEFINE_MARKET_POTENTIAL,
    articles.DO_FIELD_RESEARCH,
    articles.ANALYSE_THE_COMPETITION,
    articles.KNOW_YOUR_CUSTOMER,
    articles.MANAGE_LANGUAGE_DIFFERENCES,
    articles.UNDERSTAND_YOUR_CUSTOMERS_CULTURE,
    articles.GET_MONEY_TO_EXPORT,
    articles.CHOOSE_THE_RIGHT_FINANCE,
    articles.GET_EXPORT_FINANCE,
    articles.RAISE_MONEY_BY_BORROWING,
    articles.BORROW_AGAINST_ASSETS,
    articles.RAISE_MONEY_WITH_INVESTMENT,
    articles.GET_GOVERNMENT_FINANCE_SUPPORT,
    articles.MAKE_EXPORTING_PLAN,
    articles.FIND_A_ROUTE_TO_MARKET,
    articles.USE_OVERSEAS_AGENT,
    articles.USE_DISTRIBUTOR,
    articles.CHOOSING_AGENT_OR_DISTRIBUTOR,
    articles.LICENCE_YOUR_PRODUCT_OR_SERVICE,
    articles.START_JOINT_VENTURE,
    articles.CONSIDER_HOW_PAID,
    articles.INVOICE_CURRENCY_AND_CONTENTS,
    articles.DECIDE_WHEN_PAID,
    articles.PAYMENT_METHODS,
    articles.INSURE_AGAINST_NON_PAYMENT,
    articles.USE_FREIGHT_FORWARDER,
    articles.USE_INCOTERMS_IN_CONTRACTS,
    articles.GET_YOUR_EXPORT_DOCUMENTS_RIGHT,
    articles.MATCH_YOUR_WEBSITE_TO_YOUR_AUDIENCE,
    articles.INTERNATIONALISE_WESBITE,
    articles.WHAT_INTERLECTUAL_PROPERTY_IS,
    articles.TYPES_OF_INTERLECTUAL_PROPERTY,
    articles.KNOW_WHAT_INTERLECTUAL_PROPERTY_YOU_HAVE,
    articles.INTERLECTUAL_PROPERTY_PROTECTION,
]


PERSONA_REGULAR_ARTICLES = [
    articles.DEFINE_MARKET_POTENTIAL,
    articles.DO_FIELD_RESEARCH,
    articles.ANALYSE_THE_COMPETITION,
    articles.UNDERSTAND_YOUR_CUSTOMERS_CULTURE,
    articles.CHOOSE_THE_RIGHT_FINANCE,
    articles.GET_EXPORT_FINANCE,
    articles.RAISE_MONEY_BY_BORROWING,
    articles.BORROW_AGAINST_ASSETS,
    articles.RAISE_MONEY_WITH_INVESTMENT,
    articles.GET_GOVERNMENT_FINANCE_SUPPORT,
    articles.LICENCE_YOUR_PRODUCT_OR_SERVICE,
    articles.FRANCHISE_YOUR_BUSINESS,
    articles.START_JOINT_VENTURE,
    articles.SETUP_OVERSEAS_OPERATION,
    articles.INSURE_AGAINST_NON_PAYMENT,
    articles.KNOW_WHAT_INTERLECTUAL_PROPERTY_YOU_HAVE,
    articles.INTERLECTUAL_PROPERTY_PROTECTION
]


GUIDANCE_MARKET_RESEARCH_ARTICLES = [
    articles.DO_RESEARCH_FIRST,
    articles.DEFINE_MARKET_POTENTIAL,
    articles.DO_FIELD_RESEARCH,
    articles.ANALYSE_THE_COMPETITION,
    articles.VISIT_TRADE_SHOW,
]


GUIDANCE_CUSTOMER_INSIGHT_ARTICLES = [
    articles.KNOW_YOUR_CUSTOMER,
    articles.MEET_YOUR_CUSTOMER,
    articles.MANAGE_LANGUAGE_DIFFERENCES,
    articles.UNDERSTAND_YOUR_CUSTOMERS_CULTURE,
]


GUIDANCE_FINANCE_ARTICLES = [
    articles.GET_MONEY_TO_EXPORT,
    articles.CHOOSE_THE_RIGHT_FINANCE,
    articles.GET_EXPORT_FINANCE,
    articles.RAISE_MONEY_BY_BORROWING,
    articles.BORROW_AGAINST_ASSETS,
    articles.RAISE_MONEY_WITH_INVESTMENT,
    articles.GET_GOVERNMENT_FINANCE_SUPPORT,
]


GUIDANCE_BUSINESS_PLANNING_ARTICLES = [
    articles.MAKE_EXPORTING_PLAN,
    articles.FIND_A_ROUTE_TO_MARKET,
    articles.USE_OVERSEAS_AGENT,
    articles.USE_DISTRIBUTOR,
    articles.CHOOSING_AGENT_OR_DISTRIBUTOR,
    articles.LICENCE_AND_FRANCHISING,
    articles.LICENCE_YOUR_PRODUCT_OR_SERVICE,
    articles.FRANCHISE_YOUR_BUSINESS,
    articles.START_JOINT_VENTURE,
    articles.SETUP_OVERSEAS_OPERATION,
]


GUIDANCE_GETTING_PAID_ARTICLES = [
    articles.CONSIDER_HOW_PAID,
    articles.INVOICE_CURRENCY_AND_CONTENTS,
    articles.DECIDE_WHEN_PAID,
    articles.PAYMENT_METHODS,
    articles.INSURE_AGAINST_NON_PAYMENT,
]

GUIDANCE_OPERATIONS_AND_COMPLIANCE_ARTICLES = [
    articles.PLAN_THE_LOGISTICS,
    articles.USE_FREIGHT_FORWARDER,
    articles.USE_INCOTERMS_IN_CONTRACTS,
    articles.GET_YOUR_EXPORT_DOCUMENTS_RIGHT,
    articles.MATCH_YOUR_WEBSITE_TO_YOUR_AUDIENCE,
    articles.INTERNATIONALISE_WESBITE,
    articles.WHAT_INTERLECTUAL_PROPERTY_IS,
    articles.TYPES_OF_INTERLECTUAL_PROPERTY,
    articles.KNOW_WHAT_INTERLECTUAL_PROPERTY_YOU_HAVE,
    articles.INTERLECTUAL_PROPERTY_PROTECTION,
]

ALL_ARTICLES = [
	DO_RESEARCH_FIRST,
	articles.DEFINE_MARKET_POTENTIAL,
	articles.DO_FIELD_RESEARCH,
	articles.ANALYSE_THE_COMPETITION,
	articles.VISIT_TRADE_SHOW,
	articles.KNOW_YOUR_CUSTOMER,
	articles.MAKE_EXPORTING_PLAN,
	articles.FIND_A_ROUTE_TO_MARKET,
	articles.USE_OVERSEAS_AGENT,
	articles.USE_DISTRIBUTOR,
	articles.CHOOSING_AGENT_OR_DISTRIBUTOR,
	articles.LICENCE_AND_FRANCHISING,
	articles.LICENCE_YOUR_PRODUCT_OR_SERVICE,
	articles.FRANCHISE_YOUR_BUSINESS,
	articles.START_JOINT_VENTURE,
	articles.SETUP_OVERSEAS_OPERATION,
	articles.GET_MONEY_TO_EXPORT,
	articles.CHOOSE_THE_RIGHT_FINANCE,
	articles.GET_EXPORT_FINANCE,
	articles.RAISE_MONEY_BY_BORROWING,
	articles.BORROW_AGAINST_ASSETS,
	articles.RAISE_MONEY_WITH_INVESTMENT,
	articles.GET_GOVERNMENT_FINANCE_SUPPORT,
	articles.CONSIDER_HOW_PAID,
	articles.INVOICE_CURRENCY_AND_CONTENTS,
	articles.DECIDE_WHEN_PAID,
	articles.PAYMENT_METHODS,
	articles.INSURE_AGAINST_NON_PAYMENT,
	articles.PLAN_THE_LOGISTICS,
	articles.USE_FREIGHT_FORWARDER,
	articles.USE_INCOTERMS_IN_CONTRACTS,
	articles.GET_YOUR_EXPORT_DOCUMENTS_RIGHT,
	articles.INTERNATIONALISE_WESBITE,
	articles.MATCH_YOUR_WEBSITE_TO_YOUR_AUDIENCE,
	articles.WHAT_INTERLECTUAL_PROPERTY_IS,
	articles.TYPES_OF_INTERLECTUAL_PROPERTY,
	articles.KNOW_WHAT_INTERLECTUAL_PROPERTY_YOU_HAVE,
	articles.INTERLECTUAL_PROPERTY_PROTECTION,
	articles.MEET_YOUR_CUSTOMER,
	articles.MANAGE_LANGUAGE_DIFFERENCES,
	articles.UNDERSTAND_YOUR_CUSTOMERS_CULTURE,
]
